### ISSUE TITLE
Seconds is based on Float

### ISSUE THREAD

**Issue by rwl** [sogno-platform/cimgen#15]
The Seconds type is based on Float:

https://cgmes.github.io/CGMES-v2_4_15/EquipmentProfile-v2_4_15-7Aug2014.html#Seconds

Setting the default value to be an integer causes an error parsing values with a decimal place, for example:

https://github.com/cgmes/micro_grid/blob/16dd7feb1f9eced20ec6537d7027889aa294e7df/BaseCase_BC/BE_v2/MicroGridTestConfiguration_BC_BE_EQ_V2.xml#L1343

`'Seconds'` was added to the list in `_set_default` in https://github.com/sogno-platform/cimgen/commit/c3868f3ea4ad876b2b5e0e18b59e6e899b2518e9

https://github.com/sogno-platform/cimgen/blob/da4e9528e5c5582a0a38130e4f2f838562f64730/python/langPack.py#L56

**Comment by m-mirz** [comment]
@dinkelbachjan PR #23 fixes the issue in cimgen for both python versions but we still need to update cimpy. Before doing that we need to decide if we already switch to the "modern python" version.

**Comment by m-mirz** [comment]
#23 is merged.
