### ISSUE TITLE
Adding few CI scripts

### ISSUE THREAD

**Issue by chicco785** [sogno-platform/cimgen#17]
**Is your feature request related to a problem? Please describe.**

More automated test = more quality and less work :)

**Describe the solution you'd like**

Have a look if any of the following CI is interesting for you:
https://github.com/zaphiro-technologies/cimgen/pull/2

in which case I will be happy to open an appropriate pr to you repo.

**Describe alternatives you've considered**

Will only merge this CI to our repo and live with that.

**Additional context**

N/A

**Comment by stv0g** [comment]
I think we can close this as well. With my recent refactorings we added more CI pipelines which uses cimgen to generate code for all languages.
