### ISSUE TITLE
Simplify dockerfile

### ISSUE THREAD

**Issue by m-mirz** [sogno-platform/cimgen#29]
I would suggest to use  `python:3-alpine`, then the 2 `apk` lines become unnecessary, I think.

_Originally posted by @guillaume-alliander in https://github.com/sogno-platform/cimgen/pull/27#discussion_r1537869310_

**Comment by stv0g** [comment]
I am currently working on overhauling the Dockerfile and Python project structure in similar fashion in did for CIMpy in https://github.com/sogno-platform/cimpy/pull/30

**Comment by stv0g** [comment]
Done
